[package]
name = "ckbtc-address"
version = "0.0.1"
description = "An algorithm which calculates BTC address for deposits to ckBTC minter"
repository = "https://github.com/research-ag/ckbtc-address"

[dependencies]
base = "0.13.6"
bitcoin = "0.1.1"

[dev-dependencies]
test = "2.0.0"
bench = "1.0.0"

[toolchain]
moc = "0.13.6"
pocket-ic = "4.0.0"