name: CI

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  test:
    name: Tests and Benchmarks
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install mops
        uses: caffeinelabs/setup-mops@v1

      - name: Make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: Show versions
        run: |
          mops --version
          $(mops toolchain bin moc) --version

      - name: Run tests
        run: mops test

      - name: Run mops bench
        run: mops bench

  fmt:
    name: Formatting Check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Prettier Check
        run: |
          npm install prettier prettier-plugin-motoko --no-save
          npx prettier --plugin prettier-plugin-motoko --check '**/*.{mo,json,md}'
